export { default as Bio } from "./Bio";
export { default as Event } from "./Event";
export { default as Groupemail } from "./Groupemail";
export { default as History } from "./History";
export { default as Home } from "./Home";
export { default as Ordersubmission } from "./Order";
export { default as Updates } from "./Updates";
export { default as Viewnotfound } from "./Viewnotfound";
export { default as Links } from "./Links";
